version: "3"
services:
 web:
  image: 'gitlab/gitlab-ee:latest'
#  restart: always
  hostname: 'gitlab.vmw.mmaks17.ru'
  environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://gitlab.vmw.mmaks17.ru'
          registry_external_url 'http://registry.vmw.mmaks17.ru'
          nginx['listen_port'] = 80
          nginx['listen_http'] = true
          nginx['proxy_set_headers'] = { 'X-Forwarded-Proto' => 'http',  'X-Forwarded-Ssl' => 'off' }
          registry['enable'] = true
          registry_external_url 'http://registry.vmw.mmaks17.ru'
          registry_nginx['listen_port'] = 80
          registry_nginx['listen_http'] = true
          gitlab_rails['gitlab_shell_ssh_port'] = 1122
          gitlab_rails['gitlab_ssh_host'] = 'git.vmw.mmaks17.ru'
          letsencrypt['enable'] = false
          nginx['redirect_http_to_https'] = false
          # LDAP
          gitlab_rails['ldap_enabled'] = true
          gitlab_rails['ldap_servers'] = YAML.load <<-'EOS' # remember to close this block with 'EOS' below
            main: #'main' is the GitLab 'provider ID' of this LDAP server
              label: 'LDAP'
              host: '<AD_IP>'
              port: 389
              uid: 'sAMAccountName'
              verify_certificates: false
              method: 'plain' # "tls" or "ssl" or "plain"
              bind_dn: 'CN=<SVC_LDAP_USER>,OU=services,OU=vmw,DC=vmw,DC=mmaks17,DC=ru'
              password: '<LDAPPASS'
              active_directory: true
              allow_username_or_email_login: true
              block_auto_created_users: false
              base: 'OU=users,OU=vmw,DC=vmw,DC=mmaks17,DC=ru'
              user_filter: ''
          EOS
        VIRTUAL_HOST: gitlab.vmw.mmaks17.ru,registry.vmw.mmaks17.ru
        VIRTUAL_PORT: 80
        GITLAB_ROOT_EMAIL: "<ADMIN@EMAIL"
        GITLAB_ROOT_PASSWORD: "<PASS>"
  ports:
    - '1180:80'
    - '11443:443'
    - '1122:22'
    - '5001:5001'
  volumes:
    - './config:/etc/gitlab'
    - './logs:/var/log/gitlab'
    - './data:/var/opt/gitlab'
